import { format, parseISO, isValid } from 'date-fns';
import { ru } from 'date-fns/locale';
import { TaxSettings, Project, DailyReport, Material } from '@/types';
import { CURRENCY_SYMBOL, DATE_FORMAT, DATETIME_FORMAT, APP_NAME } from '@/constants';

export function formatDate(dateString: string, formatStr: string = DATE_FORMAT): string {
  try { const date = parseISO(dateString); if (!isValid(date)) return dateString; return format(date, formatStr, { locale: ru }); } catch { return dateString; }
}
export function formatDateTime(dateString: string): string { return formatDate(dateString, DATETIME_FORMAT); }
export function getTodayISO(): string { return new Date().toISOString().split('T')[0]; }
export function getNowISO(): string { return new Date().toISOString(); }
export function formatCurrency(amount: number): string { return new Intl.NumberFormat('ru-BY', { style: 'currency', currency: 'BYN', minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(amount); }
export function formatCurrencyCompact(amount: number): string { if (amount >= 1000000) return (amount / 1000000).toFixed(1) + 'М ' + CURRENCY_SYMBOL; if (amount >= 1000) return (amount / 1000).toFixed(0) + 'к ' + CURRENCY_SYMBOL; return formatCurrency(amount); }
export function parseCurrency(str: string): number { const cleaned = str.replace(/[^\d.,-]/g, '').replace(',', '.'); const parsed = parseFloat(cleaned); return isNaN(parsed) ? 0 : parsed; }
export function calculateTax(income: number, settings: TaxSettings): number { switch (settings.regime) { case 'NPD': return income * (settings.npdRate / 100); case 'IP': return income * (settings.ipRate / 100); case 'OOO': return income * 0.05; default: return 0; } }
export function calculateVat(amount: number, isVatPayer: boolean): number { if (!isVatPayer) return 0; return amount * 0.2; }
export function calculateNetIncome(grossIncome: number, settings: TaxSettings): number { const tax = calculateTax(grossIncome, settings); const vat = calculateVat(grossIncome, settings.isVatPayer); return grossIncome - tax - vat; }
export function getTaxDescription(settings: TaxSettings): string { switch (settings.regime) { case 'NPD': return `НПД: ${settings.npdRate}% с дохода`; case 'IP': return `ИП (УСН доходы): ${settings.ipRate}%${settings.isVatPayer ? ' + НДС 20%' : ''}`; case 'OOO': return `ООО: УСН 5%/15% или ОСНО 20%+НДС`; default: return ''; } }
export function calculateProjectFinances(project: Project, reports: DailyReport[], materials: Material[]) { const totalMaterialsCost = materials.reduce((sum, m) => sum + m.totalPrice, 0); const totalLaborCost = reports.reduce((sum, r) => sum + (r.workersPresent * 8 * 50), 0); const totalExpenses = totalMaterialsCost + totalLaborCost; const tax = calculateTax(project.budget, project.taxSettings); const vat = calculateVat(project.budget, project.taxSettings.isVatPayer); const netProfit = project.paidAmount - totalExpenses - tax - vat; return { budget: project.budget, paid: project.paidAmount, remaining: project.budget - project.paidAmount, materialsCost: totalMaterialsCost, laborCost: totalLaborCost, totalExpenses, tax, vat, netProfit, margin: project.budget > 0 ? ((project.budget - totalExpenses - tax - vat) / project.budget) * 100 : 0 }; }
export function generateId(): string { return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`; }
export function validatePhone(phone: string): boolean { const cleaned = phone.replace(/\D/g, ''); return (cleaned.length === 12 && cleaned.startsWith('375')) || (cleaned.length === 10 && cleaned.startsWith('80')); }
export function formatPhone(phone: string): string { const cleaned = phone.replace(/\D/g, ''); if (cleaned.length === 12 && cleaned.startsWith('375')) return `+375 (${cleaned.slice(3, 5)}) ${cleaned.slice(5, 8)}-${cleaned.slice(8, 10)}-${cleaned.slice(10)}`; if (cleaned.length === 10 && cleaned.startsWith('80')) return `+375 (${cleaned.slice(2, 4)}) ${cleaned.slice(4, 7)}-${cleaned.slice(7, 9)}-${cleaned.slice(9)}`; return phone; }
export function calculateProgress(reports: DailyReport[], project: Project): number { if (!reports.length) return 0; const daysSinceStart = Math.ceil((new Date().getTime() - new Date(project.startDate).getTime()) / (1000 * 60 * 60 * 24)); return Math.min(100, Math.round((reports.length / Math.max(daysSinceStart, 1)) * 100)); }
export function formatReportNumber(report: DailyReport, index: number): string { return `№${index + 1} от ${formatDate(report.date)}`; }
export function generateShareText(report: DailyReport, project: Project): string { const lines = [`📋 ${APP_NAME} — Ежедневный отчет`, `🏗 ${project.name}`, `👤 Заказчик: ${project.clientName}`, `📅 ${formatDate(report.date)}`, `🌤 Погода: ${getWeatherLabel(report.weather)} ${report.temperature}°C`, ``, `✅ СДЕЛАНО:`, report.workDone || '—', ``, `📋 ПЛАН НА ЗАВТРА:`, report.workPlan || '—', ``, `👷 Людей на объекте: ${report.workersPresent}`, `⏱ Человеко-часов: ${report.manHours}`, `` ]; if (report.materialsUsed.length) { lines.push(`📦 ИСПОЛЬЗОВАНО:`); report.materialsUsed.forEach(m => lines.push(`  • ${m.materialName}: ${m.quantity} ${m.unit}`)); lines.push(``); } if (report.materialsDelivered.length) { lines.push(`🚚 ПОСТУПЛО:`); report.materialsDelivered.forEach(m => lines.push(`  • ${m.materialName}: ${m.quantity} ${m.unit} (${m.supplier})`)); lines.push(``); } if (report.issues) { lines.push(`⚠️ ПРОБЛЕМЫ/ЗАМЕЧАНИЯ:`); lines.push(report.issues); lines.push(``); } if (report.clientDecisions) { lines.push(`🤝 РЕШЕНИЯ ЗАКАЗЧИКА:`); lines.push(report.clientDecisions); lines.push(``); } lines.push(`👷 Прораб: ${report.foremanName}`, `📸 Фото: ${report.photos.length}`, `---`, `Сгенерировано в ${APP_NAME}`); return lines.join('\n'); }
function getWeatherLabel(weather: string): string { const labels: Record<string, string> = { sunny: '☀️ Солнечно', cloudy: '☁️ Облачно', rain: '🌧️ Дождь', snow: '❄️ Снег', windy: '💨 Ветрено' }; return labels[weather] || weather; }
export function sortProjects(projects: Project[]): Project[] { return [...projects].sort((a, b) => { const statusOrder: Record<string, number> = { active: 0, planning: 1, paused: 2, completed: 3, cancelled: 4 }; const aOrder = statusOrder[a.status] ?? 5; const bOrder = statusOrder[b.status] ?? 5; if (aOrder !== bOrder) return aOrder - bOrder; return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(); }); }